on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
    - name: Make Request
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://c8000-selection-wizard.vercel.app/'
        method: 'GET'